# Autogenerated file.
# Do not edit.
# Do not change location.

message("Setting RBDL for linux-64")

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)


set(RBDL_INCLUDE_DIRS 	"${ROOT_DIR}/include/rbdl;" CACHE INTERNAL "" FORCE)

set(RBDL_LIBRARIES 	"${ROOT_DIR}/lib/linux-64/librbdl.a;"
			"${ROOT_DIR}/lib/linux-64/addons/urdfreader/librbdl_urdfreader.a;"
			CACHE INTERNAL "" FORCE)

set(RBDL_TARGET "RBDL" CACHE INTERNAL "" FORCE)

set(RBDL_PACKAGE_FOUND "TRUE" CACHE INTERNAL "" FORCE)

set(RBDL_DEPENDS "" CACHE INTERNAL "" FORCE)
 
